# Site settings
title: "Sholley's Blast Shop"
description: "Sandblasting, media blasting, custom woodwork, metalwork, and welding"

url: "http://www.sholleysblastshop.com"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed